config/routes.rb
Rails.application.routes.draw do

  root 'jobs#index', as: :home

  get 'pages' => 'pages#index'
  get 'category/:slug' => 'categories#show'
  get 'affiliates/wait' => 'affiliates#wait'
  get 'api/:token/jobs.:format', to: 'api#list', as: 'api', constraints: { format: /json|xml|yaml/ }
  get 'search', to: 'jobs#search', as: 'search'

  resources :affiliates
  resources :posts
  resources :jobs

  devise_for :users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

end

app/models/job.rb
require 'carrierwave/orm/activerecord'
require 'valid_email'

class Job < ActiveRecord::Base
  belongs_to :category
  mount_uploader :logo, JobLogoUploader

  extend FriendlyId
  friendly_id :slug_candidates, use: :slugged

  ## validation ###

  validates :category, presence: true
  validates :employment_type, presence: true
  validates :company, presence: true
  validates :position, presence: true
  validates :description, presence: true, length: { minimum: 50 }
  validates :how_to_apply, presence: true, length: { minimum: 25 }
  validates :email, presence: true, email: true

  ## active record callbacks ###

  before_create :set_expires_at_value, :set_token_value

  ## constants ##

  EMPLOYMENT_TYPES = {
    'Full Time'   => 'full-time',
    'Part Time'   => 'part-time',
    'Freelance'   => 'freelance',
    'Internship'  => 'internship'
  }

  ## methods ##

  # Try building a slug based on the following fields in
  # increasing order of specificity.
  def slug_candidates
    [
      [:company, :location, :id, :position]
    ]
  end

  # Get all active jobs
  # @param object  options
  # @param integer options[:category]   The category id
  # @param integet options[:affiliate]  The affiliate id
  # @param integer options[:max]        Maximum number of jobs to be fetched
  # @param integer options[:count]      true for for count query
  # @return collection|integer
  def self.get_active_jobs(options = {})
    options = { category: nil, affiliate: nil, max: nil, count: nil }.merge(options)

    query = self
      .where('jobs.expires_at > ?', Time.now.strftime('%Y-%m-%d %H:%M:%S'))
      .where('jobs.is_activated = ?', 1)
      .order('jobs.created_at DESC')

    if options[:category].present?
      query = query.where('jobs.category_id = ?', options[:category])
    end

    if options[:affiliate].present?
      query = query.joins('LEFT JOIN `categories` ON categories.id = jobs.category_id')
        .joins('LEFT JOIN `affiliates_categories` ON affiliates_categories.category_id = categories.id')
        .where('affiliates_categories.affiliate_id = ?', options[:affiliate])
    end

    if options[:max].present?
      query = query.take(options[:max])
    end

    if options[:count].present?
      return query.count
    end

    return query
  end

  # Count all active jobs
  # @param object  options
  # @param integer options[:category]   The category id
  # @param integet options[:affiliate]  The affiliate id
  # @param integer options[:max]        Maximum number of jobs to be fetched
  # @param integer options[:count]      true for for count query
  # @return integer
  def self.count_active_jobs(options = {})
    options = { category: nil, affiliate: nil, max: nil, count: nil }.merge(options)
    options[:count] = true
    self.get_active_jobs(options)
  end

  # Convert active record list to hash
  def self.as_hash(active_jobs)
    data = Hash.new
    active_jobs.each do |job|
      # non_friendly_url = job_url({ id: job.id })
      friendly_url = Rails.application.routes.url_helpers.job_url(job, :host => Rails.application.config.action_mailer.default_url_options[:host])
      data[friendly_url] = {
        category:     job.category.name,
        type:         Job::EMPLOYMENT_TYPES.key(job.employment_type),
        company:      job.company,
        logo:         job.logo_url,
        url:          job.url,
        position:     job.position,
        location:     job.location,
        description:  job.description,
        how_to_apply: job.how_to_apply,
        expires_at:   job.expires_at.strftime('%Y-%m-%d')
      }
    end
    return data
  end

  protected
    def set_expires_at_value
      if self.expires_at.nil?
        self.expires_at = Time.new + (30 * 24 * 60 * 60)
      end
    end

    def set_token_value
      if self.token.nil?
        value = self.email + rand(11111..99999).to_s
        self.token = Digest::SHA1.hexdigest value
      end
    end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: [:show, :edit, :update, :destroy]

  # GET /jobs
  # GET /jobs.json
  def index
    @categories = Category.get_with_jobs
    @categories.each do |category|
      category.active_jobs = Job.get_active_jobs({ category: category.id, max: Rails.application.config.max_jobs_on_homepage })
      category.no_of_jobs = Job.count_active_jobs({ category: category.id })
    end
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
  end

  # GET /jobs/new
  def new
    @job = Job.new
  end

  # GET /jobs/1/edit
  def edit
  end

  # POST /jobs
  # POST /jobs.json
  def create
    @job = Job.new(job_params)

    respond_to do |format|
      if @job.save
        format.html { redirect_to @job, notice: 'Job was successfully created.' }
        format.json { render :show, status: :created, location: @job }
      else
        format.html { render :new }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jobs/1
  # PATCH/PUT /jobs/1.json
  def update
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to @job, notice: 'Job was successfully updated.' }
        format.json { render :show, status: :ok, location: @job }
      else
        format.html { render :edit }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job.destroy
    respond_to do |format|
      format.html { redirect_to jobs_url, notice: 'Job was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # GET /search
  def search
    # @query = params[:query].gsub!(/[^a-zA-Z0-9 ]/, '');
    @query = params[:query];
    keywords = @query.split(' ');

    qb = Job.order('created_at DESC')
      .where('expires_at > ?', Time.now.strftime('%Y-%m-%d %H:%M:%S'))
      .where('is_activated = ?', 1)

    keywords.each do |keyword|
      value = '%' + keyword + '%'
      qb = qb.where('company LIKE ? OR position LIKE ? OR location LIKE ?', value, value, value)
    end

    @jobs = qb.page(params[:page]).per(Rails.application.config.max_jobs_on_category) # Use `kaminari`

    render :search
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_params
      params.require(:job).permit(:employment_type, :company, :logo, :url, :position, :location, :description, :how_to_apply, :token, :is_public, :is_activated, :email, :expires_at, :category_id)
    end
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_form.html.erb
<% new_mode = !@job.created_at.present? %>

<%= form_for(@job, html: { :multipart => true }) do |f| %>
  <% if @job.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@job.errors.count, "error") %> prohibited this job from being saved:</h2>

      <ul>
      <% @job.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :category_id %> <span class="required">*</span><br>
    <%= f.collection_select :category_id, Category.all, :id, :name, { prompt: true }, { class: "form-control" } %>
  </div>

  <div class="field">
    <%= f.label :employment_type %> <span class="required">*</span><br>
    <%= f.select(:employment_type, options_for_select(Job::EMPLOYMENT_TYPES, @job.employment_type), { prompt: true }, { class: "form-control" }) %>
  </div>

  <div class="field">
    <%= f.label :company %> <span class="required">*</span><br>
    <%= f.text_field :company, size: 30, class: "form-control" %>
  </div>

  <div class="field">
    <%= f.label :logo %><br>
    <%= f.file_field :logo %>
    <% if @job.logo? %>
      <br>
      <br>
      <%= image_tag @job.logo_url(:thumb) %>
    <% end %>
  </div>

  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url, size: 45, class: "form-control" %>
  </div>

  <div class="field">
    <%= f.label :position %> <span class="required">*</span><br>
    <%= f.text_field :position, class: "form-control" %>
  </div>

  <div class="field">
    <%= f.label :location %> <span class="required">*</span><br>
    <%= f.text_field :location, class: "form-control" %>
  </div>

  <div class="field">
    <%= f.label :description %> <span class="required">*</span><br>
    <%= f.text_area :description, rows: 10, cols: 60, class: "form-control" %>
  </div>

  <div class="field">
    <%= f.label :how_to_apply %>? <span class="required">*</span><br>
    <%= f.text_area :how_to_apply, rows: 5, cols: 60, class: "form-control" %>
  </div>

  <div class="field">
    <%= f.label :email %> <span class="required">*</span><br>
    <%= f.text_field :email, size: 35, class: "form-control" %>
  </div>

  <div class="field">
    <%= f.check_box :is_public %>
    <%= f.label :is_public %>?<br>
    Whether the job can also be published on affiliate websites or not.
  </div>

  <div class="actions">
    <% if new_mode %>
      <%= f.submit "Create Job", class: "btn btn-success btn-lg" %>
    <% else %>
      <%= f.submit "Update Job", class: "btn btn-primary btn-lg" %>
      <%= link_to 'View Job', @job, class: "btn btn-warning" %>
    <% end %>
    <%= link_to 'Cancel & Back', jobs_path, class: "btn btn-default" %>
  </div>
<% end %>

app/views/jobs/edit.html.erb
<h1>Edit Job - <%= @job.position %>, <%= @job.location %></h1>

<%= render 'form' %>

app/views/jobs/index.html.erb
<div class="jumbotron search-panel">
  <h2>
    <label for="search-keywords">Search for a Job</label>
  </h2>
  <form class="form-inline" action="<%= search_path %>" method="get">
    <input type="text" name="query" class="form-control" id="search-keywords" aria-describedby="help-block" placeholder="Type at least 2 characters...">
    <button type="submit" class="btn btn-primary btn-lg" id="search-button">Search</button>
    <span id="help-block" class="help-block">Enter some keywords (company, country, position, ...)</span>
  </form>
</div>
<table class="table table-striped table-hover">
  <tbody>
    <% @categories.each do |category| %>
      <tr class="category" align="left">
        <th colspan="8">
          <%= link_to category.name, :controller => 'categories', :action => 'show', :slug => category.slug %>
        </th>
      </tr>
      <% category.active_jobs.each do |job| %>
        <tr>
          <td><%= Job::EMPLOYMENT_TYPES.key(job.employment_type) %></td>
          <td><%= link_to job.position, job %></td>
          <td><%= link_to job.company, job.url, { target: '_blank' } %></td>
          <td><%= job.location %></td>
          <td><%= job.created_at.strftime('%Y-%m-%d') %></td>
          <td><%= link_to 'Show', job %></td>
          <td><%= link_to 'Edit', edit_job_path(job) %></td>
          <td><%= link_to 'Delete', job, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
      <% if category.no_of_jobs > 1 %>
        <tr>
          <td colspan="8" class="more-jobs">
            <p>and <%= link_to category.no_of_jobs.to_s + ' more', :controller => 'categories', :action => 'show', :slug => category.slug %></p>
          </td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

app/views/jobs/new.html.erb
<h1>Post A Job</h1>

<%= render 'form' %>

app/views/jobs/search.html.erb
<h1>Search Result for "<%= @query %>"</h1>

<% if @jobs.length > 0 %>
  <table class="table table-striped table-hover">
    <thead>
      <tr>
        <th>Type</th>
        <th>Company</th>
        <th>Position</th>
        <th>Location</th>
        <th>Posted at</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @jobs.each do |job| %>
        <tr>
          <td><%= Job::EMPLOYMENT_TYPES.key(job.employment_type) %></td>
          <td><%= link_to job.position, job %></td>
          <td><%= link_to job.company, job.url, { target: '_blank' } %></td>
          <td><%= job.location %></td>
          <td><%= job.created_at.strftime('%Y-%m-%d') %></td>
          <td><%= link_to 'Show', job %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <div class="digg_pagination pull-left">
    <div class="page_info">
      <%= page_entries_info @jobs %>
    </div>
    <%= paginate @jobs %>
  </div>
<% else %>
  <p class="bg-block bg-danger">There is no job found.</p>
<% end %>

<%= link_to 'View all jobs', jobs_path, class: "btn btn-warning pull-right" %>

app/views/jobs/show.html.erb
<h1><%= @job.position %> - <%= @job.location %></h1>
<p class="text-muted">
  <strong>Company:</strong> <%= link_to @job.company, @job.url, { target: '_blank' } %>,
  posted on <%= @job.created_at.strftime('%Y-%m-%d') %>,
  expired on <%= @job.expires_at.strftime('%Y-%m-%d') %>
</p>
<p>
  <span class="label label-primary"><%= Job::EMPLOYMENT_TYPES.key(@job.employment_type) %></span>
  <span class="label label-warning"><%= @job.category.name %></span>
</p>

<% if @job.logo.present? %>
  <p class="pull-right">
    <%= link_to image_tag(@job.logo_url(:thumb)), @job.logo_url, { target: '_blank' } %>
  </p>
<% end %>

<p>
  <strong>Description:</strong>
  <%= simple_format(@job.description) %>
</p>

<p>
  <strong>How to apply:</strong>
  <%= simple_format(@job.how_to_apply) %>
</p>

<p>
  <strong>Email:</strong>
  <%= @job.email %>
</p>

<%= link_to 'Back', jobs_path, class: 'btn btn-default' %>
<%= link_to 'Edit', edit_job_path(@job), class: 'btn btn-primary' %>