config/routes.rb
Rails.application.routes.draw do

  root 'jobs#index', as: :home

  get 'pages' => 'pages#index'
  get 'category/:slug' => 'categories#show'
  get 'affiliates/wait' => 'affiliates#wait'
  get 'api/:token/jobs.:format', to: 'api#list', as: 'api', constraints: { format: /json|xml|yaml/ }
  get 'search', to: 'jobs#search', as: 'search'

  resources :affiliates
  resources :posts
  resources :jobs

  devise_for :users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Jobeet</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="navbar navbar-inverse">
    <div class="container">
      <div class="navbar-header">
        <a href="<%= home_path %>" class="navbar-brand">Jobeet</a>
      </div>
      <div class="navbar-right">
        <a href="<%= new_job_path %>" class="btn btn-success">
          <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
          Post A Job
        </a>
      </div>
      <div class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <li class="active">
            <a href="<%= home_path %>">Home</a>
          </li>
          <li>
            <a href="<%= jobs_path %>">Jobs</a>
          </li>
          <li>
            <a href="#">Sign Up</a>
          </li>
          <li>
            <a href="#">Login</a>
          </li>
        </ul>
      </div>
    </div>
  </div>
  <div class="container">
    <% if alert.present? %>
      <div class="alert alert-warning" role="alert"><%= notice %></div>
    <% end %>
    <% if alert.present? %>
      <div class="alert alert-danger" role="alert"><%= alert %></div>
    <% end %>
    <%= yield %>
  </div>
  <div class="footer">
    <div class="container">
      <div class="navbar-left">
        <a href="#">About Jobeet</a>
        <span>|</span>
        <a href="<%= new_affiliate_path %>">Become An Affiliate</a>
      </div>
      <div class="navbar-right text-muted">&copy; 2016 Jobeet Tutorial with Ruby 2.1 & Rails 4.1</div>
    </div>
  </div>
</body>
</html>